package com.databuck.constants;

public enum DataSourceType {
	MYSQL, HDFS, VERTICA, S3, FILESYSTEM, ORACLE, HIVE,CLOUDERAHIVE, MSSQL, POSTGRES, 
	MSSQLACTIVEDIRECTORY, FILEMANAGEMENT, CASSANDRA, AMAZONREDSHIFT, HIVEKERBEROS,ORACLERAC,MAPRFS,MAPRDB,
	TERADATA,HIVEKNOX, FILESYSTEMBATCH,SNOWFLAKE, S3BATCH, Postgres, Teradata, DERIVED, BIGQUERY, AZURESYNAPSEMSSQL,
	S3IAMROLEBATCH, S3IAMROLEBATCHCONFIG, AZUREDATALAKESTORAGEGEN1, MAPRHIVE, AZUREDATALAKESTORAGEGEN2, AZUREDATALAKESTORAGEGEN2BATCH,DATABRICKSDELTALAKE
}
