/* Adding new tables to migrate properties from files to database */

DROP TABLE IF EXISTS `databuck_property_details`;
DROP TABLE IF EXISTS `databuck_properties_master`;

create table if not exists databuck_properties_master (
property_category_id int not null auto_increment,
property_category_name varchar(1000) not null UNIQUE,
description text,
created_at datetime,
PRIMARY KEY (property_category_id)
) engine=innodb auto_increment=1 default charset=latin1;

create table if not exists databuck_property_details (
property_id int not null auto_increment,
property_category_id int not null,
property_name varchar(2500) not null UNIQUE,
property_value text,
description text,
is_mandatory_field varchar(10) default 'N',
is_password_field varchar(10) default 'N',
is_value_encrypted varchar(10) default 'N',
property_default_value text,
property_data_type varchar(500),
prop_requires_restart varchar(10) default 'N',
last_updated_at datetime,
PRIMARY KEY (property_id),
FOREIGN KEY (property_category_id)
 	REFERENCES databuck_properties_master (property_category_id)
) engine=innodb auto_increment=1 default charset=latin1;


/* Insert property categories */
insert into databuck_properties_master(property_category_name,created_at) values ('appdb',now());
insert into databuck_properties_master(property_category_name,created_at) values ('resultsdb',now());
insert into databuck_properties_master(property_category_name,created_at) values ('activedirectory',now());
insert into databuck_properties_master(property_category_name,created_at) values ('cluster',now());
insert into databuck_properties_master(property_category_name,created_at) values ('license',now());
insert into databuck_properties_master(property_category_name,created_at) values ('mongodb',now());
insert into databuck_properties_master(property_category_name,created_at) values ('dbdependency',now());
insert into databuck_properties_master(property_category_name,created_at) values ('dynamicvariable',now());

/* AppDb properties */
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'deploymentMode','local','Property to mention in which mode application is running local, hdfs or s3','Y','N','N','local','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'isActiveDirectoryAuthentication','N','Property to enable or disable ActiveDirectory Authentication','Y','N','N','N','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'manualDBMigrationEnabled','N','Property to specify if database migration or upgrade is done manually','Y','N','N','N','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'mapr.ticket.enabled','N','Property to enable or disable usage of ticket during script trigger','Y','N','N','N','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'isRuleCatalogDiscovery','N','Property to enable or disable RuleCatalog Discovery','N','N','N','N','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'isTestApprovalRequired','N','Property to enable approval to execute unit testing validation','N','N','N','N','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'isURLSecurityRequired','N','Property to enable security for all the databuck UI Urls','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'isTemplateUpdationSupported','N','Property to mention template updation supported or not when created using Rest API','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'dynamicVariableEnabled','N','Property to enable dynamic variable logic for cisco','N','N','N','N','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'exportImportMode','N','Property to enable/disable Import Export feature','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'snowflake.securemode','N','Property to enable/disable snowflake secure mode','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'maxActiveJobCount','4','Property to specify maximum Active spark jobs to run in parallel','N','N','N','16','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'dq.unsupported.datatypes','array,map,tuple','Property to write comma separated list of unsupported datatypes in table metadata','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'csvWriteLimit','100000','Propety to specify number of output/result records written into csv file','N','N','N','100','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'databuck.result.fileType','csv','Property to specify the type in which file has to be saved [Eg. parquet, csv]','N','N','N','csv','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'custom_sampling_count','10000','Custom Sampling count for analysis','N','N','N','10000','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'custom.execution.record.count','1000','Specify the number of records to be executed for test run','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'RuleCatalogApproverRole','','Property to configure role name which can approve rule catalog','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'serviceAuthenticationType','','Property to select authentication type for Rest API''s (token or ldap)','N','N','N','token','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'serviceLdapGroup','','Property to specify the ldap group of the users who can access the REST API','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'application.server.path','','Property to specify the tomcat bin folder, used to restart tomcat from UI','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'file.pattern.regex','N','Property to enable file name pattern detection based on regex','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'filemonitoring.fullfile.check','N','Property to enable/disable fileMonitoring full file data check','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'datadrift.potentialduplicates.enabled','N','Property to enable or disable detection of potential duplicates in datadrift','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'advancedrules.reasonability.disable','N','Property to disable reasonability advanced rules generation during template analysis','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'advancedrules.colrltnship.uniquedatacount','50','Property to specify eligible unique data count of columns to generate column relationship rules.','N','N','N','50','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'rootcause.analysis.check','Y','Property to enable or disable RootCause Analysis check','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'rootcause.analysis.threshold','30','Root cause analysis threshold value','N','N','N','6','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'hdfs_result_directory','','Property to mention the hdfs directory where result files will be stored, when deployment mode is hdfs','N','N','N','','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'hdfs.accesslog.path','N','Access log folder path in hdfs','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'gssJass_File_Path','','Property to specify the jass file path to connect to hdfs filesystem to download result files','N','N','N','','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'hdfs_uri','','Property to specify the hdfs URI to connect to hdfs filesystem to download result files','N','N','N','','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'aging.exceptionData.limit','5000000','Property to specify a record limit upto which aging report generation is allowed','N','N','N','5000000','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'aging.fullLoad.exceptionDataPath','','Property to specify the location to store the aging exception report for full Load Data','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'s3CsvPath','','Property to mention the s3 path where result files will be stored, when deployment mode is s3','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'s3.bucketname','','aws s3 bucket name','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'s3.aws.accessKey','','Aws accesskey to connect to s3','N','N','N','','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'s3.aws.secretKey','','aws secret key to connect to s3','N','Y','Y','','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'s3.decrypt.passphrase','','Property to mention the passphrase used to decrypt the encrypted files','N','Y','Y','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'jbpm.workflow.url','','Property to mention jbpm workflow rest url','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'jbpm.workflow.user','','Property to mention jbpm workflow rest url username','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'jbpm.workflow.password','','Property to mention jbpm workflow rest url password','N','Y','Y','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'ruledefectcode.rest.url','','Property to hold the external rest api url for getting the defect code of rule','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'colibra.metadata.url','','Colibra url to get the metadata from steel - Wellsfargo specific','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'aver.report.link','http://<host>:<port>/home/loading?token=','Property to mention aver report link','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'date.format.timeliness','dd-MMM-yyyy','date format for timeliness','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'date.format.Incremental','yyyy-MM-dd HH:mm:ss','date format for incremental load ','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'date.format.Incremental.db','MM/dd/yyyy','date format for incremental load in database','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'number.Format','US','number format','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'number.FormatCol','','number format col','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'match.string','[a-zA-Z]','regex for string','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'match.dateRegexFormate','\d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])*,(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])\-\d{4},(0?[1-9]|1[012])\/(0?[1-9]|[12][0-9]|3[01])\/\d{4},[0-9]{4}-(0[1-9]|1[0-2])-([0-2][0-9]|[3][0-1]) [0-2]?[0-9]:[0-6]?[0-9]:[0-6]?[0-9]','date regex format','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'match.dateRegexFormateD','^(?:(?:31(/|-|.)(?:0?[13578]|1[02]|(?:Jan|Mar|May|Jul|Aug|Oct|Dec)))1|(?:(?:29|30)(/|-|.)(?:0?[1,3-9]|1[0-2]|(?:Jan|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec))2))(?:(?:1[6-9]|[2-9]d)?d{2})$|^(?:29(/|-|.)(?:0?2|(?:Feb))3(?:(?:(?:1[6-9]|[2-9]d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1d|2[0-8])(/|-|.)(?:(?:0?[1-9]|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep))|(?:1[0-2]|(?:Oct|Nov|Dec)))4(?:(?:1[6-9]|[2-9]d)?d{2})$','date Regex Format','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'match.numberRegex','^\d+([,\.]\d+)?$','number Regex','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'match.numberRegexUS','^-?(0|[1-9][0-9]{0,2}(?:(,[0-9]{3})*|[0-9]*))(.[0-9]+){0,1}$','number Regex US','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'match.numberRegexEU','^-?(0|[1-9][0-9]{0,2}(?:(.[0-9]{3})*|[0-9]*))(,[0-9]+){0,1}$','number regex EU','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'match.numberRegexUSD','^-?(0|[1-9][0-9]{0,2}(?:(,[0-9]{3})*|[0-9]*))(.[0-9]+){0,1}$','number Regex for US','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'match.numberRegexEUD','^-?(0|[1-9][0-9]{0,2}(?:(.[0-9]{3})*|[0-9]*))(,[0-9]+){0,1}$','number Regex for EU','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'killAutomatically','Y','Property to enable kill the overtimejob automatically','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'killTime','01:00','Property to mention duration of job considered overtime to kill job. Format HH:MM, it is duration not Time','N','N','N','01:00','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'retention.dataquality.days','80','Property to mention no of days of dataquality data has to retained','N','N','N','30','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'retention.datamatching.days','80','Property to mention no of days of datamatching data has to retained','N','N','N','30','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'SNSNotifications','N','Property to enable/disable SQS Notifications','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'sns.notifications.iamrole','N','Property to enable/disable SNS Notifications using IAMRole','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'sns.aws.topicARN','','Property to mention SNS Topic ARN','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'sns.topic.region','','Property to mention SNS Topic region','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'sns.aws.accessKey','','aws accesskey for sns','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'sns.aws.secretKey','','aws secret key for sns','N','Y','Y','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'sqs.notifications','N','Property to enable/disable SQS Notifications','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'sqs.notifications.queue.url','','Property to mention SQS queue Url','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'sqs.notifications.queue.region','','Property to mention SQS queue region','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'smtp_host','','host details for smtp - send email','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'smtp_port','587','port details for smtp - send email','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'smtp_mode','','Property to specify the smtp mode auth/noAuth','N','N','N','noAuth','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'smtp_username','','user name for smtp - send email','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'smtp_password','','password for smtp - send email','N','Y','Y','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'mailSender','','mail recepients details to send email','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'mailRecepients','','mail sender details to send email','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'mailxEmailNotification','N','Property to enable email notification via mailx','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'filemonitor.sns.aws.topicARN','','Property to specify the SNS Topic ARN for File monitor','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'filemonitor.sns.aws.topic.region','','Property to specify the SNS Topic region for File monitor','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'filemonitor.aws.accessKey','','aws secret key for File monitor SNS Topic','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='appdb'),'filemonitor.aws.secretKey','','aws secret key for file monitor SNS Topic','N','Y','Y','','string','N',NOW());


/* activedirectory properties */
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'Context.INITIAL_CONTEXT_FACTORY','com.sun.jndi.ldap.LdapCtxFactory','initial context','Y','N','N','','string','Y', now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'Context.PROVIDER_URL','ldap://<host>:<port>','provider url','Y','N','N','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'Context.SECURITY_AUTHENTICATION','simple','security authentication','Y','N','N','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'Context.SECURITY_PRINCIPAL','','user id','Y','N','N','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'Context.SECURITY_CREDENTIALS','','security credentials','Y','Y','Y','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'searchBase','','searchBase','Y','N','N','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'Domainforalluser','','domain name for all users','Y','N','N','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'Loginuid','','Loginuid','Y','N','N','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'userObjectClass','account','user object class','Y','N','N','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'attributetofetch','cn','attributetofetch','Y','N','N','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'domainPosition','3','domainPosition','Y','N','N','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'rolePosition','4','rolePosition','Y','N','N','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'groupFilter','1AOE','groupFilter','Y','N','N','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'defaultrole','','defaultrole of an user','N','N','N','','string','Y',now());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='activedirectory'),'sorPosition','','sorPosition','N','N','N','','string','Y',now());
 
/* cluster properties */
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='cluster'),'deploymode','2','spark deploy mode local mode value is 2, cluster mode value is 1','Y','N','N','2','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='cluster'),'hive_mode','remote','Property to enable/ disable hive context. deploymode =1 i.e, cluster mode and hive_mode value is cluster starts sparksession with hivesupport enabled.','Y','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='cluster'),'kerberos_enabled','N','Property to enable or diable kerberos','Y','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='cluster'),'numberOfPartitions','100','Property to specify number of partitions to configure in spark job','Y','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='cluster'),'app_mode','0','app_mode value 0 indicates local and value 1 indicates mongo db','Y','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='cluster'),'EMRCluster','N','Property to enable/disable connect to EMR cluster','N','N','N','N','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='cluster'),'hive_context_enabled','N','Property to enable or disable data read via Hive context','N','N','N','N','string','N',NOW());

/* license properties */ 
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='license'),'LicenseKey','3mX+7tfOwspQJ9Q644q4ZXujI+7Mn115dUNpFF+WdUg=','Databuck License Key','Y','N','N','None','string','Y',NOW());
 
/* mongodb properties */ 
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='mongodb'),'ipAddress','','ipaddress to connect to mongodb','Y','N','N','','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='mongodb'),'port','','port details of mongodb','Y','N','N','','string','Y',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='mongodb'),'databaseName','','mongodb database name to be connected','Y','N','N','','string','Y',NOW());
 
/* dbdependency properties */ 
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='dbdependency'),'DT','CN-idDataSchema','DataTemplate to Connection Hierarchy','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='dbdependency'),'VC','DT-idData','Validation to DataTemplate Hierarchy','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='dbdependency'),'LDS','CN-idDataSchema','ListDataSource to Connection Hierarchy','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='dbdependency'),'LDA','CN-idDataSchema','ListDataApplication to Connection Hierarchy','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='dbdependency'),'LDD','CN-idDataSchema','ListDataDefinition to Connection Hierarchy','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at) values((select property_category_id from databuck_properties_master where property_category_name='dbdependency'),'CN','','Connection Hierarchy','N','N','N','','string','N',NOW());

/* dynamicvariable properties */
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at)values((select property_category_id from databuck_properties_master where property_category_name='dynamicvariable'),'db.driver','','driver details to connect to postgressql','Y','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at)values((select property_category_id from databuck_properties_master where property_category_name='dynamicvariable'),'db.url','','url to connect to postgressql','Y','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at)values((select property_category_id from databuck_properties_master where property_category_name='dynamicvariable'),'db.user','','user details to connect to postgressql','Y','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at)values((select property_category_id from databuck_properties_master where property_category_name='dynamicvariable'),'db.pwd','','pwd to connect to postgressql','Y','Y','Y','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at)values((select property_category_id from databuck_properties_master where property_category_name='dynamicvariable'),'target.table.dynamicFilterQuery','','','N','N','N','','string','N',NOW());
insert into databuck_property_details(property_category_id,property_name,property_value,description,is_mandatory_field,is_password_field,is_value_encrypted,property_default_value,property_data_type,prop_requires_restart,last_updated_at)values((select property_category_id from databuck_properties_master where property_category_name='dynamicvariable'),'src.table.dynamicFilterQuery','','','N','N','N','','string','N',NOW());
