CREATE TABLE `DATA_QUALITY_INDEX` (
 `id` BIGINT NOT NULL AUTO_INCREMENT ,
  `validation_check_name` varchar(100) NOT NULL,
  `validation_check_id` bigint(20) NOT NULL,
  `date` date NOT NULL,
  `run` bigint(20) NOT NULL,
  `overall_status` varchar(20) DEFAULT NULL,
  `overall_score` varchar(20) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `record_count_status` varchar(20) DEFAULT NULL,
  `record_count_score` varchar(20) DEFAULT NULL,
  `null_count_status` varchar(20) DEFAULT NULL,
  `null_count_score` varchar(20) DEFAULT NULL,
  `all_fields_status` varchar(20) DEFAULT NULL,
  `all_fields_score` varchar(20) DEFAULT NULL,
  `user_selected_fields_status` varchar(20) DEFAULT NULL,
  `user_selected_fields_score` varchar(20) DEFAULT NULL,
  `numerical_field_status` varchar(20) DEFAULT NULL,
  `numerical_field_score` varchar(20) DEFAULT NULL,
  `string_field_status` varchar(20) DEFAULT NULL,
  `string_field_score` varchar(20) DEFAULT NULL,
  `record_anomaly_status` varchar(20) DEFAULT NULL,
  `record_anomaly_score` varchar(20) DEFAULT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
